version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  build:
    working_directory: ~/homepage
    executor: node/default
    steps:
      - checkout
      - node/install
      - run: npm run build   
workflows:
  build-homepage:
    jobs:
      - build
